---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/sonarr/tvseries:/tv #optional
      - ~/sonarr/downloadclient-downloads:/downloads #optional
      - ~/sonarr/data:/config
    ports:
      - 8989:8989
    restart: unless-stopped