---
version: "2.1"
services:
  sonarr:
    image: wernight/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/qbittorrent/config:/config
      - ~/qbittorrent/torrents:/torrents #optional
      - ~/qbittorrent/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    restart: unless-stopped