version: '3'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  frontend:
    # add this if the network is already existing!
    # external: true
  backend:

services:

  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud-db:/var/lib/mysql
      - ./nextcloud-docroot:/var/www/html
    ports:
      - 4080:80
    environment:
      - MYSQL_PASSWORD=your secure pw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=redis
      - APACHE_DISABLE_REWRITE_IP
      - VIRTUAL_HOST=cloud.DOMAIN
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=NginxProxyManager
      - OVERWRITECLIURL=https://nextcloud.website.com
      - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.website.com
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your secure pw
      - MYSQL_PASSWORD=your secure pw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
