 # Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_USER: username
      MARIADB_PASSWORD: mypass2
    volumes:
      - ~/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080