version: '2.4'

services:

  pdns-recursor:
    image: pschiffe/pdns-recursor:${RECURSOR_TAG:-latest}
    networks:
      pdns:
        ipv4_address: 172.6.0.21
        aliases:
          - pdns
    ports:
      - "8085:8085"
      - "8085:8085/udp"
      - "8082:8082"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2

  mariadb:
    image: mariadb:10.6
    networks:
      pdns:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/powerdns/mariadb:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mypw
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=mypw
      - MYSQL_USERNAME=root
    # healthcheck:
    #   test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
    #   timeout: 10s
    #   retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    networks:
      - pdns
    ports:
      - '8988:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro

  pdns-master:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: hostname.website.com
    networks:
      pdns:
        ipv4_address: 172.6.0.20
        aliases:
          - pdns
    extra_hosts:
      - 'hostname.website.com:10.0.0.13'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    environment:
      - PDNS_gmysql_password=mypw
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=172.6.0.20
      - PDNS_webserver_password=secret2
      - PDNS_webserver_allow_from=172.6.0.0/24
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=172.6.0.21
      - PDNS_only_notify=172.6.0.21
    depends_on:
      - mariadb

  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi
    networks:
      pdns:
        aliases:
          - pdns-admin-uwsgi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_PASSWORD='mypw'
      - PDNS_VERSION=4.5
      - PDNS_API_KEY=secret
    depends_on:
      - mariadb
      - pdns-master

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    networks:
      - pdns
    ports:
      - '8989:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pdns-admin-uwsgi

networks:
  pdns:
    ipam:
      config:
        - subnet: 172.6.0.0/16
          gateway: 172.6.0.1

volumes:
  mariadb: